AlphaHealthApp/urls.py
from django.urls import path
from . import views

app_name = 'AlphaHealthApp'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('PatientLogin/', views.PatientLogin, name = 'PatientLogin'),
    path('PatientLoginPage/', views.PatientLoginPage, name = 'PatientLoginPage'),
    path('NewPatient/', views.NewPatient, name = 'NewPatient'),
    path('PatientUpdate/', views.PatientUpdate, name = 'PatientUpdate'),
    path('CreatePatient/', views.CreatePatient, name = 'CreatePatient'),

    path('CreateAppointment/', views.CreateAppointment, name = 'CreateAppointment'),
    path('ViewAppointment/', views.ViewAppointment, name = 'ViewAppointment'),

    path('DoctorView/', views.DoctorView, name = 'DoctorView'),
    path('ViewAllAppointment/', views.ViewAllAppointment, name = 'ViewAllAppointment'),

]

AlphaHealthProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AlphaHealthApp.urls')),
]

AlphaHealthApp/models.py
from django.db import models

class Users(models.Model):
    userName = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'Users'

    

class UsersInfo(models.Model):
    userName = models.CharField(max_length=30)
    firstName = models.CharField(max_length=30)
    lastName  = models.CharField(max_length=30)
    age = models.IntegerField()

    class Meta:
        verbose_name_plural = 'UsersInfo'


class UsersAppointments(models.Model):
    userName = models.CharField(max_length=30)
    date = models.CharField(max_length=10)
    time  = models.CharField(max_length=8)
    reason = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'UsersAppointments'

AlphaHealthApp/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse 
import json
from AlphaHealthApp.models import Users
from AlphaHealthApp.models import UsersInfo
from AlphaHealthApp.models import UsersAppointments


def index(request):
    return render(request, 'AlphaHealthApp/index.html')

def PatientLogin(request):
    return render(request, 'AlphaHealthApp/patient_login.html')

def DoctorView(request):
    return render(request, 'AlphaHealthApp/doctor_page.html')

def NewPatient(request):
    return render(request, 'AlphaHealthApp/patient_register.html')


def CreatePatient(request):
    usrName = request.POST['userName']
    userPswd = request.POST['userPswd']
    new_fname = request.POST['newFName']
    new_lname = request.POST['newLName']
    new_age = request.POST['newAge']    

    newUser = Users(userName = usrName, password = userPswd) 
    newUser.save() 
    
    newUserInfo = UsersInfo(userName = usrName, firstName = new_fname, lastName = new_lname, age =new_age) 
    newUserInfo.save()    

    return JsonResponse({'status' : 'successful'})


def PatientUpdate(request):
    usrName = request.POST['userName']
    new_fname = request.POST['newFName']
    new_lname = request.POST['newLName']
    new_age = request.POST['newAge']

    updateUser = UsersInfo.objects.get(userName=usrName)
    updateUser.firstName = new_fname
    updateUser.lastName = new_lname
    updateUser.age = new_age

    updateUser.save()

    
    return JsonResponse({'uFName':updateUser.firstName,'uLName':updateUser.lastName,'uAge':updateUser.age})



def PatientLoginPage(request):
    patientID = request.POST['PatientUserID']
    patientPswd = request.POST['PatientPassword']

    UsersList = Users.objects.all()
    existingUsers = []
    for patient in UsersList:
        existingUsers.append({patient.userName:patient.password})

    try:
        usrInfo = UsersInfo.objects.get(userName=patientID)
    except:
        return HttpResponse("User Doesnt exist. Please head back and register.Or contact Admin for assistance.")

    context = {'patientID' : patientID, 'isAuthd' : True, 'firstname' : usrInfo.firstName,
            'lastname' : usrInfo.lastName, 'age' : usrInfo.age}
    return render(request, 'AlphaHealthApp/patient_page.html', context)


def CreateAppointment(request):
    usrName = request.POST['userName']
    apptDate = request.POST['apptDate']
    apptTime = request.POST['apptTime']
    apptReason = request.POST['apptReason']

    newAppt = UsersAppointments(userName = usrName, date = apptDate, time = apptTime, reason = apptReason) 
    newAppt.save()   

    return JsonResponse({'status':'success', 'ApptDate' : apptDate, 'ApptTime':apptTime, 'ApptReason':apptReason})

def ViewAppointment(request):    
    usrName = request.POST['usrName']
    usrAppts = UsersAppointments.objects.filter(userName=usrName)
    usrApptList = []
    for appt in usrAppts:
        usrApptList.append([appt.date, appt.time, appt.reason])

    return JsonResponse({'userAppts' : usrApptList})


def ViewAllAppointment(request):    
    usrAppts = UsersAppointments.objects.all()
    usrApptList = []
    for appt in usrAppts:
        usrApptList.append([appt.userName, appt.date, appt.time, appt.reason])

    return JsonResponse({'userAppts' : usrApptList})

AlphaHealthApp/templates/AlphaHealthApp/doctor_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Doctor Home</title>
</head>
<body>
    <h1>Doctor's HomePage</h1>

    <h3>All User's Appointments: </h3>
    <h4 id = 'AllAppts'></h4>

<script>
    $.ajax({
        url: '/ViewAllAppointment/',
        method: 'POST',
        data: {
            csrfmiddlewaretoken: "{{ csrf_token }}",
        },
        success : function(resultResponse){
            console.log(resultResponse)
            for(let i = 0; i<= resultResponse.userAppts.length; i++)
            if(resultResponse.userAppts[i] != undefined)  $('#AllAppts').append("<p>" + resultResponse.userAppts[i] +"</p>");
        }
    });
</script>

</body>
</html>

AlphaHealthApp/templates/AlphaHealthApp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>AlphaHealth Home</title>
</head>
<body>

    <h1>Welcome To Alpha Health</h1>

    <br/>
    <br/>

    <h3>Who are you?</h3>
    
    <form action="/PatientLogin" method="get">
        <button type = "submit" value="Submit">Patient</button>
    </form>

    <br/>

    <form action="/DoctorView" method="get">
        <button type = "submit" value="Submit">Doctor</button>
    </form>
    
</body>
</html>

AlphaHealthApp/templates/AlphaHealthApp/patient_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Patient Login</title>
</head>
<body>

    <h1>Please enter you credentials or create an account</h1>

    <br/>
    <br/>

    <h3>LOGIN : </h3>
    

    <form action="/PatientLoginPage/" method="POST">
        {% csrf_token %} 
        <h4>UserID : </h4> <input type="text"  id="PatientUserID" name = "PatientUserID" required>
        <br/>
        <h4>Password : </h4> <input type="password"  id="PatientPassword" name = "PatientPassword" required>
        <br/>
        <button type = "submit" value="Submit" id = "PatientLoginButton">LOGIN!</button>
    </form>




    <p><i>If you are a new user, create an account</i></p>

    <form action="/NewPatient" method="get">
        <button type = "submit" value="Submit">Create Account</button>
    </form>

    

</body>
</html>

AlphaHealthApp/templates/AlphaHealthApp/patient_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Welcome!</title>
</head>
<body>

<h1>Patient's Profile:</h1>

Hi there!!! {{patientID}}. Welcome back.

<a href = "{% url 'AlphaHealthApp:PatientLogin'%}">Logout</a>

<h3 id = "updatePrompt"></h3>
<h5>Profile Details : </h5>
UserName : <p id = 'uname'>&nbsp;&nbsp;{{patientID}}</p>
First Name : <p id = 'fname'>&nbsp;&nbsp;{{firstname}}</p>
Last Name : <p id = 'lname'>&nbsp;&nbsp;{{lastname}}</p>
Age : <p id = 'age'>&nbsp;&nbsp;{{age}}</p> <br>

<br/>


<h5>Update profile details(<i>This uses jquery AJAX. </i>)</h5>

First Name : <input type = 'text' id = 'new_fname'>
Last Name : <input type = 'text' id = 'new_lname'>
Age : <input type = 'text' id = 'new_age'>

<button id = 'updateProfileDetails'>Update!</button>


<br>
<br>

<h3>My all Appointments: </h3>
<h4 id = 'myAllAppts'></h4>



<br>
<br>


<h3>Appointment Status: </h3>
<h5 id = 'apptStatus'></h5>
<h5 id = 'apptStatusDate'></h5>
<h5 id = 'apptStatusTime'></h5>
<h5 id = 'apptStatusReason'></h5>



<h3>Create Appointments : </h3>

Date : <input type = 'text' id = 'apptDate'>(format:dd-mm-yyyy)<br>
Time  : <input type = 'text' id = 'apptTime'>(format:hh:mm:ss)<br>
Appointment Reason : <input type = 'textarea' id = 'apptReason'><br>
<br>
<button id = 'createAppt'>Fix Appointment</button>




<script>

$('#updateProfileDetails').click(function(){        
    $.ajax({
        url: '/PatientUpdate/',
        method:  "POST",
        data: {
            csrfmiddlewaretoken: "{{ csrf_token }}",
            userName : $('#uname').html().replace('&nbsp;&nbsp;',''),
            newFName : $('#new_fname').val(),
            newLName : $('#new_lname').val(),
            newAge : $('#new_age').val(),
        },   
        success: function(resultResponse){
            $('#updatePrompt').text("You're details are updated!!!!");
            $('#fname').text(resultResponse.uFName);
            $('#lname').text(resultResponse.uLName);
            $('#age').text(resultResponse.uAge);
        }          
    });    
});





$('#createAppt').click(function(){        
    $.ajax({
        url: '/CreateAppointment/',
        method:  "POST",
        data: {
            csrfmiddlewaretoken: "{{ csrf_token }}",
            userName : $('#uname').html().replace('&nbsp;&nbsp;',''),
            apptDate : $('#apptDate').val(),
            apptTime : $('#apptTime').val(),
            apptReason : $('#apptReason').val(),
        },   
        success: function(resultResponse){
            $('#apptStatus').text("Appointment registered!!!!");
            $('#apptStatusDate').text("Date : " +resultResponse.ApptDate);
            $('#apptStatusTime').text("Time : " +resultResponse.ApptTime);
            $('#apptStatusReason').text("Reason : " +resultResponse.ApptReason);
        }          
    });    
});





$.ajax({
    url: '/ViewAppointment/',
    method: 'POST',
    data: {
        csrfmiddlewaretoken: "{{ csrf_token }}",
        usrName : $('#uname').html().replace('&nbsp;&nbsp;',''),
    },
    success : function(resultResponse){
        console.log(resultResponse)
        for(let i = 0; i<= resultResponse.userAppts.length; i++)
        if(resultResponse.userAppts[i] != undefined)  $('#myAllAppts').append("<p>" + resultResponse.userAppts[i] +"</p>");
    }
});


</script>



</body>
</html>

AlphaHealthApp/templates/AlphaHealthApp/patient_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Register</title>
</head>
<body>
    
    <h2 id = 'status'></h2>

    <br>

    <h3>Create an account...</h3>
    

    First Name : <input type = 'text' id = 'new_fname'><br>
    Last Name : <input type = 'text' id = 'new_lname'><br>
    Age : <input type = 'text' id = 'new_age'><br>
    UserName : <input type = 'text' id = 'new_usrname'><br>
    Password : <input type = 'password' id = 'new_pswd'><br>
    <br>
    <button id = 'registerPatient'>Create Account</button>

    <br><br>

    <a href = "{% url 'AlphaHealthApp:PatientLogin'%}">Login page</a>




<script>

    $('#registerPatient').click(function(){ 
        $.ajax({
            url: '/CreatePatient/',
            method:  "POST",
            data: {
                csrfmiddlewaretoken: "{{ csrf_token }}",
                userName : $('#new_usrname').val(),
                userPswd : $('#new_pswd').val(),
                newFName : $('#new_fname').val(),
                newLName : $('#new_lname').val(),
                newAge : $('#new_age').val(),
            },
            success: function(resultResponse){
                $('#status').text("Account Created successfully");
            }    
        });
    });

</script>

</body>
</html>